### ISSUE TITLE
Pydantic validation doesn't work when set  table=True 

### ISSUE THREAD

**Issue by johnsxiong** [tiangolo/sqlmodel#225] opened 2022-01-16 10:55 UTC
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

import sqlalchemy as sa
from sqlmodel import Field, SQLModel


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    secret_name: str
    age: int = Field(gt=100, sa_column=sa.Column(sa.BigInteger()))


print(Hero()) # >>>  id=None
```

### Description

It didn‘t raise a ValidationError Exception When create a hero object without any params.

### Operating System

macOS

### SQLModel Version

0.0.6

### Python Version

3.9.5

**Comment by lovetoburnswhen** [comment] 2022-01-28 03:36
Duplicate of #134

**Closed** 2022-02-06 16:01 UTC
Labels: question
