### ISSUE TITLE
`Field(nullable=True)` is ignored due to recent changes released in version 0.0.7

### ISSUE THREAD

**Issue by br-allstreet** [tiangolo/sqlmodel#420] opened 2022-08-28 22:04 UTC
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

from sqlmodel import Field, Session, SQLModel, create_engine

class Hero(SQLModel, table=True):
  id: Optional[int] = Field(default=None, primary_key=True)
  # This should not be nullable
  name: Optional[str] = Field(default=None, nullable=False)

hero = Hero()
engine = create_engine("sqlite:///database.db")

SQLModel.metadata.create_all(engine)
with Session(engine) as session:
  session.add(hero)
  session.commit()
  session.refresh(hero)
  print(hero)
```

### Description

* Create a hero model with a non-nullable column by assigning it to `Field(nullable=True)`
* Create a hero instance without setting the column
* Save the instance to the DB. Should get an error but the hero instance saves successfully.

I believe this issue was introduced here: https://github.com/tiangolo/sqlmodel/commit/9830ee0d8991ffc068ffb72ccead2427c84e58ee#r82434170

### Operating System

macOS

### SQLModel Version

0.0.7

### Python Version

Python 3.10.5

**Comment by JonasKs** [comment] 2022-08-29 08:56
Yeah, there's something iffy here, but I can't reproduce your example.

In the [test](https://github.com/tiangolo/sqlmodel/blob/main/tests/test_tutorial/test_create_db_and_table/test_tutorial001.py#L13), it is asserted that `name VARCHAR NOT NULL`. 

[This test](
https://github.com/tiangolo/sqlmodel/blob/main/docs_src/tutorial/create_db_and_table/tutorial001.py#L8) still pass when changing into this:

```diff
from typing import Optional

from sqlmodel import Field, SQLModel, create_engine


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
-   name: str
+   name: Optional[str] = Field(default=None, nullable=False)
    secret_name: str
    age: Optional[int] = None


sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url, echo=True)

SQLModel.metadata.create_all(engine)

```

Which is good.

However, it also passes when changing name in to `nullable=True`. So `nullable` properties have some weird behavior.

```diff
from typing import Optional

from sqlmodel import Field, SQLModel, create_engine


class Hero(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
-   name: str
+   name: Optional[str] = Field(default=None, nullable=True)
    secret_name: str
    age: Optional[int] = None


sqlite_file_name = "database.db"
sqlite_url = f"sqlite:///{sqlite_file_name}"

engine = create_engine(sqlite_url, echo=True)

SQLModel.metadata.create_all(engine)

```

**Comment by br-allstreet** [comment] 2022-08-29 11:38
> I've submitted a new test that tests nullable fields, and it seems correct to me. See PR #423.

I believe I have confirmed and addressed the issue in https://github.com/tiangolo/sqlmodel/pull/424.

**Comment by JonasKs** [comment] 2022-08-29 12:22
Aha, I understand now. Seems like a weird pattern to set a default value, but not allow it.. 

As a side note, please either branch out from the PR / ask for branch permissions to add more commits / add the original author as a [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) when you copy/paste code from another PR 😊

**Comment by br-allstreet** [comment] 2022-08-29 12:31
> You might type is as optional so that you can create the object without setting all the fields.
> 
> Happy to do either. If you give me branch permissions, I can make my change to your existing branch.
> 
> > Aha, I understand now. Seems like a weird pattern to set a default value, but not allow it.. To me it seems like you just shouldn't type it as optional.
> > As a side note, please either branch out from the PR / ask for branch permissions to add more commits / add the original author as a [co-author](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) when you copy/paste code from another PR 😊

Added you as a co-author:
https://github.com/tiangolo/sqlmodel/pull/424/commits/00cebd28c39a818f884194680531f78fac9158a3

**Comment by JonasKs** [comment] 2022-08-29 12:57
Gave you access to mine, but up to you. I assume you have to rebase those commits into one commit to get it merged anyway 😄

**Comment by JonasKs** [comment] 2022-08-29 14:07
Since you added me as a co-author on the wrong commit, I honestly think you should just finish your PR, copy over the changes you'd like into my PR, and then close yours. Then git history will be correct, and git commit history could be two commits with the correct authors.

**Comment by br-allstreet** [comment] 2022-08-29 14:58
I assumed he would squash the commits. But I will commit to your PR.

**Comment by tiangolo** [comment] 2022-08-30 16:20
Thanks for the report @JonasKs! And thanks for the help to you both.

https://github.com/tiangolo/sqlmodel/pull/423 is now merged. I tweaked it a bit with extra cases and fixes. It will be available in the next version released in the next hours. SQLModel `0.0.8` :rocket:

**Closed** 2022-09-10 00:13 UTC
Labels: bug, answered
