### ISSUE TITLE
Tutorial: Creating DB within WSL on Windows

### ISSUE THREAD

**Issue by sffjunkie** [tiangolo/sqlmodel#452] opened 2022-09-22 15:30 UTC
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
Create database as described in the tutorial using "DB browser" on an WSL drive.
```

### Description

If following the tutorial on WSL2, using the suggested sqlite DB management tool "DB browser" you get strange errors when creating the database on a WSL2 volume (it looks like it is due WSL2 does not support file locking)

You can work around this issue by creating the DB on the `C:\` drive and linking to the file from within the WSL volume.

Either
- add a warning to the docs
- or probably the best option, close this issue and leave it for people searching in the future.

### Operating System

Windows

### Operating System Details

WSL2

### SQLModel Version

0.0.8

### Python Version

Python 3.10.6

**Comment by phi-friday** [comment] 2022-09-26 23:46
I also use wsl2 and often sqlite, but I have never experienced an error caused by wsl2. What exactly did the error occur?

**Comment by tiangolo** [comment] 2022-11-14 06:54
Thanks for adding that info here! 🤓

I'll close the issue as you say, but thanks for adding the note for others that come later! ☕

**Closed by tiangolo** 2022-11-14 06:54 UTC
Labels: question
